### ISSUE TITLE
Is (version) or greater helper methods

### ISSUE THREAD

**Issue by dbwiddis** [cegredev/josi#3]
Feature request:  a common version use case is determining a minimum and/or maximum range of versions.  It would be useful for you to add a few helper methods that do not require an explicit list.

For example, you currently have `public boolean is(OS... operatingSystems)`.   I'd suggest adding `public boolean isAtLeast(OS operatingSystem)`.

**Comment by cegredev** [comment]
Great idea! I'm going to address this further in the PR.
